# on:
#   schedule:
#     - cron: '5 2 * * *' # Run daily at 2:05 am
name: SIAHL Season Data Refresh
run-name: ${{ github.actor }} dev/testing data refresh ğŸš€
on: [push]
jobs:
  Refresh-Data:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - name: Install dependencies
        run: Rscript code/setup_env.R
      - name: Run Update Script
        run: |
          pwd
      - run: echo "ğŸ This job's status is ${{ job.status }}."